version: "v0.5.0-6f28c19"
hub:
  db:
    type: postgres

auth:
  type: dummy

singleuser:
  memory:
    guarantee: 1G
    limit: 1G
  image:
    name: kuberlytics/jupyterhub-user
  storage:
    type: hostPath
    extraVolumes:
      - name: home
        hostPath:
          path: /data/homes/{username}
    extraVolumeMounts:
      - name: home
        mountPath: /home/jovyan

admin:
  users:
    # infrastructure
    - jkuruzovich
